wallpaper {
  monitor = DP-3
  path = ~/pictures/wallpaper/wallpaper2.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/pictures/wallpaper/wallpaper1.png
  fit_mode = cover
}

splash = false
ipc = true
